'use strict';
const E=ForuEngine,$=id=>document.getElementById(id);let memories=[];try{memories=JSON.parse(localStorage.getItem('foru-memories-v2')||'[]');if(!Array.isArray(memories))memories=[];}catch{}
let s=E.initial(memories),index=-1,auto=null,tick=null,tts=false,speechToken=0,audioAvailable='speechSynthesis'in window;
function cancelOutput(){clearInterval(tick);tick=null;speechToken++;if(audioAvailable)speechSynthesis.cancel();}
function persist(){try{localStorage.setItem('foru-memories-v2',JSON.stringify(s.memories));}catch{$('storageNote').textContent='当前浏览器禁止存储；记忆仅在本次页面有效。';}}
function dispatch(type,extra={}){const before=s.remaining;const uninterrupted=['NOISE','TICK','EDIT_MEMORY','DELETE_MEMORY','SAVE_MEMORY','SKIP_MEMORY'].includes(type);if(!uninterrupted)cancelOutput();s=E.reduce(s,{type,...extra});persist();render();if(s.remaining&&(!uninterrupted||before!==s.remaining&&type!=='TICK'))play();}
function play(){clearInterval(tick);const token=++speechToken,words=s.remaining;tick=setInterval(()=>{if(token!==speechToken)return; s=E.reduce(s,{type:'TICK',count:1});$('caption').textContent=s.heard; $('unheard').textContent=s.remaining||'本段已呈现完毕';if(!s.remaining){clearInterval(tick);tick=null;renderStatus();}},90);if(tts&&audioAvailable&&!s.mode.includes('文字')){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(words);u.lang='zh-CN';u.rate=1;u.onend=()=>{};speechSynthesis.speak(u);}}
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function renderStatus(){$('stateTitle').textContent=({Dormant:'随时可以开始',Speaking:'我在说，随时打断',Waiting:'我等你',Listening:'我在听',Confirming:'等你确认',Handoff:'设备接力',Closed:'这段陪伴已结束','Silent Act':'安静在场','Barge-in':'听你改口'})[s.state]||s.state;$('stateSub').textContent=s.reason;$('sessionText').textContent=s.session?(s.active?'伴随中 · ':'已结束 · ')+s.session:'伴随尚未开启';$('modeTag').textContent=s.device+' · '+s.mode;$('decision').textContent=s.decision;$('decisionWhy').textContent=s.reason;$('orb').className='orb '+(s.state==='Speaking'?'speaking':'waiting');}
function render(){renderStatus();$('sceneTitle').textContent=E.scenes[s.scene].name;$('sceneDesc').textContent=E.scenes[s.scene].desc;$('progress').textContent=Math.max(index+1,0)+' / '+E.flow.length;$('caption').textContent=s.heard||'你想说时，我在。';$('unheard').textContent=s.remaining||'没有待播内容';$('sceneList').replaceChildren();E.scenes.forEach((sc,i)=>{const n=node('button','scene '+(s.scene===i?'active':''));n.type='button';n.append(node('span','num',String(i+1)));const wrap=node('span');wrap.append(node('strong','',sc.name),node('small','',sc.time));n.append(wrap);n.onclick=()=>jump(i);$('sceneList').append(n);});
$('dialog').replaceChildren();for(const m of s.transcript.slice(-6)){const r=node('div','msg '+m.type),b=node('div','bubble');b.append(node('div','speaker',m.type==='user'?'你':m.type==='ai'?'张怀民':'场景变化'),node('div','',m.text));r.append(b);$('dialog').append(r);} $('dialog').scrollTop=$('dialog').scrollHeight;
$('ledger').replaceChildren();if(!s.ledger.length)$('ledger').append(node('p','sub','打断后，这里会保留已呈现与未呈现的分界。'));s.ledger.forEach(l=>{const n=node('div','ledger-item');n.append(node('b','','已呈现：'+(l.heard||'尚未开始')),node('small','','未呈现：'+(l.unheard||'无')),node('small','',l.status));$('ledger').append(n);});
$('taskList').replaceChildren();s.tasks.forEach(t=>{const n=node('div','ledger-item');n.append(node('b','',t.text),node('small','',t.status));$('taskList').append(n);});if(!s.tasks.length)$('taskList').append(node('p','sub','今晚的任务会跟着你走。'));
$('confirmation').hidden=!s.pending;if(s.pending)$('draftText').textContent=s.pending.to+'：'+s.pending.text;
$('memoryCandidate').hidden=!s.candidate;$('memory').replaceChildren();if(!s.memories.length)$('memory').append(node('p','sub','暂无长期记忆。到家后，你决定留下什么。'));s.memories.forEach(m=>{const n=node('div','ledger-item'),input=node('input','memory-input');input.value=m.text;input.setAttribute('aria-label','编辑偏好 '+m.scope);const save=node('button','btn','保存修改');save.onclick=()=>{if(input.value.trim())dispatch('EDIT_MEMORY',{id:m.id,text:input.value.trim()});};const del=node('button','btn','删除');del.onclick=()=>dispatch('DELETE_MEMORY',{id:m.id});n.append(input,node('small','',m.source+' · '+m.scope),save,del);$('memory').append(n);});
$('nextBtn').textContent=index>=E.flow.length-1?'流程已结束':'下一步：'+E.flow[Math.min(index+1,E.flow.length-1)][1];$('nextBtn').disabled=index>=E.flow.length-1;$('autoBtn').textContent=auto?'暂停自动演示':'自动演示完整流程';$('ttsBtn').textContent=tts?'声音体验：开':'声音体验：关';$('ttsBtn').setAttribute('aria-pressed',String(tts));$('closeBtn').disabled=!s.active;}
function next(){if(index<E.flow.length-1){index++;dispatch(E.flow[index][0]);}if(index===E.flow.length-1)stopAuto();}
function stopAuto(){clearInterval(auto);auto=null;$('autoBtn').textContent='自动演示完整流程';}
function reset(){stopAuto();cancelOutput();s=E.initial(s.memories);index=-1;render();}
function jump(scene){stopAuto();cancelOutput();const target=[0,8,12,15][scene];s=E.initial(s.memories);for(let i=0;i<target;i++)s=E.reduce(s,{type:E.flow[i][0]});index=target-1;next();}
$('autoBtn').onclick=()=>{if(auto){stopAuto();return;}if(index>=E.flow.length-1)reset();next();auto=setInterval(next,3500);render();};$('nextBtn').onclick=()=>{stopAuto();next();};$('resetBtn').onclick=reset;$('closeBtn').onclick=()=>{stopAuto();dispatch('CLOSE');};$('ttsBtn').onclick=()=>{tts=!tts;cancelOutput();render();if(tts&&s.remaining)play();};$('debugBtn').onclick=()=>{$('brain').hidden=!$('brain').hidden;document.querySelector('.grid').classList.toggle('no-brain',$('brain').hidden);$('debugBtn').textContent=$('brain').hidden?'查看决策与账本':'收起决策与账本';};
for(const b of document.querySelectorAll('[data-event]'))b.onclick=()=>{stopAuto();dispatch(b.dataset.event);};
$('commandForm').onsubmit=e=>{e.preventDefault();stopAuto();const value=$('command').value.trim();if(!value)return;const rules=[[/开启|陪我/,'START'],[/等等|北门|不对/,'INTERRUPT'],[/确认/,'CONFIRM'],[/取消/,'CANCEL'],[/发消息|告诉|跟小林说/,'DRAFT'],[/上车|开车/,'DRIVE'],[/安静|咖啡馆/,'QUIET'],[/耳机断/,'UNPLUG'],[/详情/,'PRIVATE'],[/到家/,'HOME'],[/记住|保存/,'SAVE_MEMORY'],[/结束/,'CLOSE'],[/安排/,'PLAN'],[/休息/,'REST'],[/想想|呃/,'PAUSE']];const found=rules.find(([re])=>re.test(value));dispatch(found?found[1]:'UNKNOWN',{text:value});$('command').value='';};
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('exportMemory').onclick=()=>download('Foru-memory.json',{version:2,memories:s.memories});$('exportLog').onclick=()=>download('Foru-session-log.json',{simulation:true,note:'事件时间与字幕游标是本地UI数据，不是语音识别或声学延迟实测。',...s});
setInterval(()=>{$('restClock').textContent=s.rest?'演示休息计时 · '+Math.max(0,Math.ceil((s.rest-Date.now())/1000))+' 秒':'等待你的下一组';},250);window.addEventListener('beforeunload',cancelOutput);document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAuto();cancelOutput();}});render();
